---
# Three node deployment:
# - PostgreSQL database
# - OMERO.server
# - OMERO.web

- hosts: omero-database
  roles:
    - role: ome.postgresql

  vars:
    postgresql_server_listen: "'*'"
    postgresql_server_auth:
      - database: omero
        user: omero
        address: 0.0.0.0/0
    postgresql_databases:
      - name: omero
    postgresql_users:
      - user: omero
        password: omero
        databases: [omero]
    postgresql_version: "11"

- hosts: omero-server
  roles:
    - role: ome.omero_server

  vars:
    omero_server_dbhost: >-
      {{ hostvars['omero-database'].ansible_eth0.ipv4.address }}
    postgresql_version: "11"


- hosts: omero-web
  roles:
    - role: ome.omero_web

  vars:
    omero_web_config_set:
      omero.web.server_list:
        - ["{{ hostvars['omero-server'].ansible_eth0.ipv4.address }}",
           4064, omero]
